---

# Access, Authentication, and Authorization

- name: "SECTION | 4.1 | Configure time-based job schedulers"
  ansible.builtin.import_tasks:
      file: cis_4.1.x.yml

- name: "SECTION | 4.2 | Configure SSH Server"
  ansible.builtin.import_tasks:
      file: cis_4.2.x.yml
  when:
      - "'openssh-server' in ansible_facts.packages"

- name: "SECTION | 4.3 | Configure privilege escalation"
  ansible.builtin.import_tasks:
      file: cis_4.3.x.yml

- name: "SECTION | 4.4 | Configure authselect"
  ansible.builtin.import_tasks:
      file: cis_4.4.x.yml

- name: "SECTION | 4.5 | Configure PAM "
  ansible.builtin.import_tasks:
      file: cis_4.5.x.yml

- name: "SECTION | 4.6.1.x | Shadow Password Suite Parameters"
  ansible.builtin.import_tasks:
      file: cis_4.6.1.x.yml

- name: "SECTION | 4.6.x | Misc. User Account Settings"
  ansible.builtin.import_tasks:
      file: cis_4.6.x.yml
