---

- name: "1.4.1 | PATCH | Ensure permissions on bootloader config are configured"
  block:
      - name: "1.4.1 | PATCH | Ensure permissions on bootloader config are configured | bios boot"
        ansible.builtin.file:
            path: "/boot/grub2/{{ item.path }}"
            owner: root
            group: root
            mode: "{{ item.mode }}"
            state: touch
            modification_time: preserve
            access_time: preserve
        loop:
            - { path: 'grub.cfg', mode: '0700' }
            - { path: 'grubenv', mode: '0600' }
            - { path: 'user.cfg', mode: '0600' }
        when: amzn2023cis_legacy_boot

      - name: "1.4.1 | PATCH | Ensure permissions on bootloader config are configured | efi boot"
        ansible.builtin.lineinfile:
            path: /etc/fstab
            regexp: '(.*\/boot\/efi\s+vfat\s+defaults,.*)umask=00\d\d,(fmask=\d\d\d\d,|)(.*$)'
            backrefs: true
            line: '\1umask=0027,fmask=0077,\3'
        when: not amzn2023cis_legacy_boot
  when:
      - amzn2023cis_rule_1_4_1
  tags:
      - level1-server
      - grub
      - patch
      - rule_1.4.1
