---

- name: "SECTION | 1.1.1.x | Disable unused filesystems"
  ansible.builtin.import_tasks:
      file: cis_1.1.1.x.yml

- name: "SECTION | 1.1.2.x | Configure /tmp"
  ansible.builtin.import_tasks:
      file: cis_1.1.2.x.yml

- name: "SECTION | 1.1.3.x | Configure /var"
  ansible.builtin.import_tasks:
      file: cis_1.1.3.x.yml

- name: "SECTION | 1.1.4.x | Configure /var/tmp"
  ansible.builtin.import_tasks:
      file: cis_1.1.4.x.yml

- name: "SECTION | 1.1.5.x | Configure /var/log"
  ansible.builtin.import_tasks:
      file: cis_1.1.5.x.yml

- name: "SECTION | 1.1.6.x | Configure /var/log/audit"
  ansible.builtin.import_tasks:
      file: cis_1.1.6.x.yml

- name: "SECTION | 1.1.7.x | Configure /home"
  ansible.builtin.import_tasks:
      file: cis_1.1.7.x.yml

- name: "SECTION | 1.1.8.x | Configure /dev/shm"
  ansible.builtin.import_tasks:
      file: cis_1.1.8.x.yml

- name: "SECTION | 1.1.9 | Disable various mounting"
  ansible.builtin.import_tasks:
      file: cis_1.1.9.yml

- name: "SECTION | 1.2 | Configure Software Updates"
  ansible.builtin.import_tasks:
      file: cis_1.2.x.yml

- name: "SECTION | 1.3 | Filesystem Integrity Checking"
  ansible.builtin.import_tasks:
      file: cis_1.3.x.yml
  when: amzn2023cis_config_aide

- name: "SECTION | 1.4 | Secure Boot Settings"
  ansible.builtin.import_tasks:
      file: cis_1.4.x.yml

- name: "SECTION | 1.5 | Additional Process Hardening"
  ansible.builtin.import_tasks:
      file: cis_1.5.x.yml

- name: "SECTION | 1.6 | Mandatory Access Control"
  ansible.builtin.import_tasks:
      file: cis_1.6.1.x.yml
  when: not amzn2023cis_selinux_disable

- name: "SECTION | 1.7 | Command Line Warning Banners"
  ansible.builtin.import_tasks:
      file: cis_1.7.x.yml

- name: "SECTION | 1.8 | Updates and Patches"
  ansible.builtin.import_tasks:
      file: cis_1.8.yml

- name: "SECTION | 1.9 | Crypto policies"
  ansible.builtin.import_tasks:
      file: cis_1.9.yml
