---

# Logging and Auditing

- name: "SECTION | 5.1.1 | Configure Logging - rsyslog"
  ansible.builtin.import_tasks:
      file: cis_5.1.1.x.yml
  when: amzn2023cis_syslog_service == 'rsyslog'

- name: "SECTION | 5.1.2 | Configure Logging - journald"
  ansible.builtin.import_tasks:
      file: cis_5.1.2.x.yml
  when: amzn2023cis_syslog_service == 'journald'

- name: "SECTION | 5.1.3 | Configure logfile perms"
  ansible.builtin.import_tasks:
      file: cis_5.1.3.yml

- name: "SECTION | 5.2.1 | Configure System Accounting (auditd)"
  ansible.builtin.import_tasks:
      file: cis_5.2.1.x.yml
  when:
      - not system_is_container

- name: "SECTION | 5.2.2 | Configure Data Retention"
  ansible.builtin.import_tasks:
      file: cis_5.2.2.x.yml

- name: "SECTION | 5.2.3 | Configure Auditd rules"
  ansible.builtin.import_tasks:
      file: cis_5.2.3.x.yml

- name: "SECTION | 5.2.4 | Configure Audit files"
  ansible.builtin.import_tasks:
      file: cis_5.2.4.x.yml

- name: "SECTION | 5.3 | Configure LogRotate"
  ansible.builtin.import_tasks:
      file: cis_5.3.yml
